version: '3'
services:

  deakin-library:
    image: deakin-library
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: deakin-library
    ports:
     - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://sit722_task10_2hd_user:amGELcekWaOWf6lIBCoF0Ax61eSQ4H9x@dpg-crbu3ctsvqrc73f46o3g-a.singapore-postgres.render.com/sit722_task10_2hd
    restart: "no"

  deakin-inventory:
    image: deakin-inventory
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: deakin-inventory
    ports:
     - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://sit722_task10_2hd_user:amGELcekWaOWf6lIBCoF0Ax61eSQ4H9x@dpg-crbu3ctsvqrc73f46o3g-a.singapore-postgres.render.com/sit722_task10_2hd
    restart: "no"
